#!/bin/bash
#date 3/20/22
#Samer El-Mehalawy
#Midterm Question five 

}
printf "Create User [-u | --username] &lt;username&gt;\n"
printf "OPTIONS\n"
printf " -u --username\username for new account (required)\n"
printf " -p --password\password for new account (required)\n"
exit 1 
}

if [ "$?" -eq 8 ]; then
echo "Username: $username"
echo "Password: $password"
else
echo "Failed to set up user account"
userdel -f "$username"
fi

ZZ
:x
:wq


